version: "3"

services:
  db:
    image: mysql:8.0.33
    ports:
      - 3306:3306
    volumes:
      - node-practice-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/
      - ./backend/node_modules/:/app/node_modules/
    tty: true
    depends_on:
      - db

volumes:
  node-practice-db:
